language: android

android:

  # Emulator Management: Create, Start and Wait
        components:
                - tools
                - platform-tools
                - build-tools-28.0.3
                - android-29
                - extra
                - sys-img-x86-android-26
rvm:
 - 2.2
 - jruby
